### ISSUE TITLE
Statusbar pkgbuild file is for cutefish-settings

### ISSUE THREAD

**Issue by samee-np** [adig-pkgs/cutefish-pkgs#1]
No comment here. Title describes cause.(Edit: package description only need to change)

**Comment by adi-g15** [comment]
> No comment here. Title describes cause.(Edit: package description only need to change)

Thanks for pointing it out @samee-np  :D

Originally most of them used the settings PKGBUILD as template, then just a %s/settings/new_name/g to replace all with new package name, missed here 😅
